name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.3'
      - run: |
          make clean build
          cp build/amd64/cgroup-exporter .
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: cgroup-exporter
